version: '3.8'
services:
  app:
    container_name: app
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
      - 5678:5678
    volumes:
      - .:/app
    env_file:
      - .envs/dev.env
    entrypoint:
      - /app/run.sh

  nginx:
    image: nginx
    ports:
      - "80:80"
        #- "443:443"
    volumes:
      #- ./nginx_ssl.conf:/etc/nginx/nginx.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl/
    depends_on:
      app:
        condition: service_started

