version: '3.8'
services:
  app:
    container_name: app
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
      - 5678:5678
    volumes:
      - .:/app
    env_file:
      - .envs/dev.env
    entrypoint:
      - /app/run.sh
