"""empty message

Revision ID: 8d6a9eb4bce2
Revises: 427d4d63bf4e
Create Date: 2024-02-12 16:43:41.617822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8d6a9eb4bce2"
down_revision = "427d4d63bf4e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("surveys", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("survey_name", sa.String(length=50), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("surveys", schema=None) as batch_op:
        batch_op.drop_column("survey_name")

    # ### end Alembic commands ###
