# Generated by Django 4.2.7 on 2023-11-20 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(help_text='Full name should contain only letters.', max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_full_name', message='Full name should contain only letters.', regex='^[A-Za-z ]+$')])),
                ('mobile_number', models.CharField(blank=True, default='', help_text='The mobile number should start with 5 and be 9 digits long.', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='The mobile number should start with 5 and be 9 digits long.', regex='^0\\d{10}$')])),
                ('email', models.EmailField(default='', help_text='The email address should be unique and valid.', max_length=254, unique=True, validators=[django.core.validators.EmailValidator])),
                ('password', models.CharField(max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
